name: Deploy and Archive Apache Server
on:
  push:
    branches:
      - main
jobs:
  deploy_and_archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker environment
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'

      - name: Build and run Docker container
        run: |
          docker build -t my-apache-server .
          docker run -d -p 80:80 my-apache-server
             - name: Wait for Apache Server to start
          run: |
          n=0
          until [ $n -ge 10 ]
          do
            curl -s http://localhost && break
            n=$[$n+1]
            sleep 5
          done
           - name: Create artifact
          run: |
          tar -czvf apache-server.tar.gz .
          mkdir -p artifacts
          mv apache-server.tar.gz artifacts/
           - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
          name: apache-server-artifact
          path: artifacts/
          
        
